### ISSUE TITLE
1.80.2 fails with undefined symbol error

### ISSUE THREAD

**Issue by jtilly** [conda-forge/openvscode-server-feedstock#36]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When I run 

```
mamba install -y openvscode-server
openvscode-server --without-connection-token --port 8888
```

I get

```
Server bound to 127.0.0.1:8888 (IPv4)
Extension host agent listening on 8888

[13:11:41] 

Error: /opt/conda/share/openvscode-server/node_modules/@vscode/spdlog/build/Release/spdlog.node: undefined symbol: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at bindings (/opt/conda/share/openvscode-server/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/node_modules/@vscode/spdlog/index.js:3:35)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at r (/opt/conda/share/openvscode-server/out/server-main.js:3:98)
    at n.load (/opt/conda/share/openvscode-server/out/server-main.js:2:1637)
    at f.load (/opt/conda/share/openvscode-server/out/server-main.js:1:12350)
    at c (/opt/conda/share/openvscode-server/out/server-main.js:3:9301)
    at Object.errorback (/opt/conda/share/openvscode-server/out/server-main.js:3:9420)
    at f.triggerErrorback (/opt/conda/share/openvscode-server/out/server-main.js:1:12644)
    at /opt/conda/share/openvscode-server/out/server-main.js:1:12395
    at n.load (/opt/conda/share/openvscode-server/out/server-main.js:2:1654)
    at f.load (/opt/conda/share/openvscode-server/out/server-main.js:1:12350)
    at c (/opt/conda/share/openvscode-server/out/server-main.js:3:9301)
    at d._loadModule (/opt/conda/share/openvscode-server/out/server-main.js:3:9429)
    at d._resolve (/opt/conda/share/openvscode-server/out/server-main.js:4:452)
    at d.defineModule (/opt/conda/share/openvscode-server/out/server-main.js:3:5524)
    at d._relativeRequire (/opt/conda/share/openvscode-server/out/server-main.js:3:6148)
    at e (/opt/conda/share/openvscode-server/out/server-main.js:3:8479)
    at A.m (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:45078)
    at new Promise (<anonymous>)
    at A (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:45058)
    at b.n (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:46173)
    at new b (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:46048)
    at A.m (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:46705)
    at A.createLogger (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:6487)
    at _e (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:150:53751)
    at ce (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:158:6143)
    at async /opt/conda/share/openvscode-server/out/server-main.js:4:11122
    at async Server.<anonymous> (/opt/conda/share/openvscode-server/out/server-main.js:13:100) {
  code: 'ERR_DLOPEN_FAILED',
  phase: 'loading',
  moduleId: '@vscode/spdlog',
  neededBy: [ '===anonymous3===' ]
}
Error: /opt/conda/share/openvscode-server/node_modules/@vscode/spdlog/build/Release/spdlog.node: undefined symbol: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at bindings (/opt/conda/share/openvscode-server/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/node_modules/@vscode/spdlog/index.js:3:35)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at r (/opt/conda/share/openvscode-server/out/server-main.js:3:98)
    at n.load (/opt/conda/share/openvscode-server/out/server-main.js:2:1637)
    at f.load (/opt/conda/share/openvscode-server/out/server-main.js:1:12350)
    at c (/opt/conda/share/openvscode-server/out/server-main.js:3:9301)
    at Object.errorback (/opt/conda/share/openvscode-server/out/server-main.js:3:9420)
    at f.triggerErrorback (/opt/conda/share/openvscode-server/out/server-main.js:1:12644)
    at /opt/conda/share/openvscode-server/out/server-main.js:1:12395
    at n.load (/opt/conda/share/openvscode-server/out/server-main.js:2:1654)
    at f.load (/opt/conda/share/openvscode-server/out/server-main.js:1:12350)
    at c (/opt/conda/share/openvscode-server/out/server-main.js:3:9301)
    at d._loadModule (/opt/conda/share/openvscode-server/out/server-main.js:3:9429)
    at d._resolve (/opt/conda/share/openvscode-server/out/server-main.js:4:452)
    at d.defineModule (/opt/conda/share/openvscode-server/out/server-main.js:3:5524)
    at d._relativeRequire (/opt/conda/share/openvscode-server/out/server-main.js:3:6148)
    at e (/opt/conda/share/openvscode-server/out/server-main.js:3:8479)
    at A.m (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:45078)
    at new Promise (<anonymous>)
    at A (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:45058)
    at b.n (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:46173)
    at new b (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:46048)
    at A.m (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:46705)
    at A.createLogger (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:92:6487)
    at _e (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:150:53751)
    at ce (/opt/conda/share/openvscode-server/out/vs/server/node/server.main.js:158:6143)
    at async /opt/conda/share/openvscode-server/out/server-main.js:4:11122
    at async Server.<anonymous> (/opt/conda/share/openvscode-server/out/server-main.js:13:100) {
  code: 'ERR_DLOPEN_FAILED',
  phase: 'loading',
  moduleId: '@vscode/spdlog',
  neededBy: [ '===anonymous3===' ]
}
Web UI available at http://localhost:8888/
[13:11:41] Extension host agent started.
[13:11:41] Started initializing default profile extensions in extensions installation folder. file:///root/.openvscode-server/extensions
[13:11:41] Completed initializing default profile extensions in extensions installation folder. file:///root/.openvscode-server/extensions
[IPC Library: Pty Host] innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/conda/share/openvscode-server/node_modules/node-pty/lib/unixTerminal.js
- /opt/conda/share/openvscode-server/node_modules/node-pty/lib/index.js
- /opt/conda/share/openvscode-server/out/bootstrap-amd.js
- /opt/conda/share/openvscode-server/out/bootstrap-fork.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/node_modules/node-pty/lib/index.js:14:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at i (/opt/conda/share/openvscode-server/out/vs/loader.js:5:98)
    at n.load (/opt/conda/share/openvscode-server/out/vs/loader.js:4:1651)
    at _.load (/opt/conda/share/openvscode-server/out/vs/loader.js:3:9105)
    at u (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9325)
    at h._loadModule (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9453)
    at h._resolve (/opt/conda/share/openvscode-server/out/vs/loader.js:6:452)
    at h.defineModule (/opt/conda/share/openvscode-server/out/vs/loader.js:5:5548)
    at y (/opt/conda/share/openvscode-server/out/vs/loader.js:6:1770)
    at v (/opt/conda/share/openvscode-server/out/vs/loader.js:4:2462)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/out/vs/platform/terminal/node/ptyHostMain.js:26:13344)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/out/vs/platform/terminal/node/ptyHostMain.js:27:17457)
    at n._createAndEvalScript (/opt/conda/share/openvscode-server/out/vs/loader.js:4:2506)
    at /opt/conda/share/openvscode-server/out/vs/loader.js:4:2147
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[IPC Library: Pty Host] innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/conda/share/openvscode-server/node_modules/node-pty/lib/unixTerminal.js
- /opt/conda/share/openvscode-server/node_modules/node-pty/lib/index.js
- /opt/conda/share/openvscode-server/out/bootstrap-amd.js
- /opt/conda/share/openvscode-server/out/bootstrap-fork.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/node_modules/node-pty/lib/index.js:14:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at i (/opt/conda/share/openvscode-server/out/vs/loader.js:5:98)
    at n.load (/opt/conda/share/openvscode-server/out/vs/loader.js:4:1651)
    at _.load (/opt/conda/share/openvscode-server/out/vs/loader.js:3:9105)
    at u (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9325)
    at Object.errorback (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9444)
    at _.triggerErrorback (/opt/conda/share/openvscode-server/out/vs/loader.js:3:9399)
    at /opt/conda/share/openvscode-server/out/vs/loader.js:3:9150
    at n.load (/opt/conda/share/openvscode-server/out/vs/loader.js:4:1668)
    at _.load (/opt/conda/share/openvscode-server/out/vs/loader.js:3:9105)
    at u (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9325)
    at h._loadModule (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9453)
    at h._resolve (/opt/conda/share/openvscode-server/out/vs/loader.js:6:452)
    at h.defineModule (/opt/conda/share/openvscode-server/out/vs/loader.js:5:5548)
    at y (/opt/conda/share/openvscode-server/out/vs/loader.js:6:1770)
    at v (/opt/conda/share/openvscode-server/out/vs/loader.js:4:2462)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/out/vs/platform/terminal/node/ptyHostMain.js:26:13344)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/out/vs/platform/terminal/node/ptyHostMain.js:27:17457)
    at n._createAndEvalScript (/opt/conda/share/openvscode-server/out/vs/loader.js:4:2506)
    at /opt/conda/share/openvscode-server/out/vs/loader.js:4:2147
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[IPC Library: Pty Host] Loading "node-pty" failed
[IPC Library: Pty Host] Error: /opt/conda/share/openvscode-server/node_modules/node-pty/build/Release/pty.node: undefined symbol: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/node_modules/node-pty/lib/unixTerminal.js:29:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/node_modules/node-pty/lib/index.js:14:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at i (/opt/conda/share/openvscode-server/out/vs/loader.js:5:98)
    at n.load (/opt/conda/share/openvscode-server/out/vs/loader.js:4:1651)
    at _.load (/opt/conda/share/openvscode-server/out/vs/loader.js:3:9105)
    at u (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9325)
    at Object.errorback (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9444)
    at _.triggerErrorback (/opt/conda/share/openvscode-server/out/vs/loader.js:3:9399)
    at /opt/conda/share/openvscode-server/out/vs/loader.js:3:9150
    at n.load (/opt/conda/share/openvscode-server/out/vs/loader.js:4:1668)
    at _.load (/opt/conda/share/openvscode-server/out/vs/loader.js:3:9105)
    at u (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9325)
    at h._loadModule (/opt/conda/share/openvscode-server/out/vs/loader.js:5:9453)
    at h._resolve (/opt/conda/share/openvscode-server/out/vs/loader.js:6:452)
    at h.defineModule (/opt/conda/share/openvscode-server/out/vs/loader.js:5:5548)
    at y (/opt/conda/share/openvscode-server/out/vs/loader.js:6:1770)
    at v (/opt/conda/share/openvscode-server/out/vs/loader.js:4:2462)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/out/vs/platform/terminal/node/ptyHostMain.js:26:13344)
    at Object.<anonymous> (/opt/conda/share/openvscode-server/out/vs/platform/terminal/node/ptyHostMain.js:27:17457)
    at n._createAndEvalScript (/opt/conda/share/openvscode-server/out/vs/loader.js:4:2506)
    at /opt/conda/share/openvscode-server/out/vs/loader.js:4:2147
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[IPC Library: Pty Host] Here are the modules that depend on it:
[IPC Library: Pty Host]% [ 'vs/platform/terminal/node/terminalProcess' ]
[13:11:51] [Error: ENOENT: no such file or directory, scandir '/root/.openvscode-server/data/logs'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/root/.openvscode-server/data/logs'
}

```

### Installed packages

```shell
conda list

# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       2_gnu    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.0.9           py310h130cc07_9    conda-forge
bzip2                     1.0.8                hf897c2e_4    conda-forge
c-ares                    1.19.1               h31becfc_0    conda-forge
ca-certificates           2023.7.22            hcefe29a_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310hf0c4615_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.3.1          py310h4c7bcd0_0    conda-forge
conda-libmamba-solver     23.3.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.3          py310h34e2850_0    conda-forge
fmt                       9.1.0                hdd96247_0    conda-forge
gettext                   0.21.1               ha18d298_0    conda-forge
icu                       72.1                 hcf00150_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
keyutils                  1.6.1                h4e544f5_0    conda-forge
krb5                      1.21.2               hc419048_0    conda-forge
ld_impl_linux-aarch64     2.40                 h2d8c526_0    conda-forge
libarchive                3.6.2                h566b526_1    conda-forge
libcurl                   8.2.1                h4e8248e_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h3557bc0_5    conda-forge
libgcc-ng                 13.1.0               h2b4548d_0    conda-forge
libgcrypt                 1.10.1               h4e544f5_0    conda-forge
libglib                   2.76.4               h0464669_0    conda-forge
libgomp                   13.1.0               h2b4548d_0    conda-forge
libgpg-error              1.47                 h5ce24db_0    conda-forge
libiconv                  1.17                 h9cdd2b7_0    conda-forge
libmamba                  1.4.2                h4a4fd89_0    conda-forge
libmambapy                1.4.2           py310hbc2a718_0    conda-forge
libnghttp2                1.52.0               h250e5c5_0    conda-forge
libnsl                    2.0.0                hf897c2e_0    conda-forge
libsecret                 0.18.8               h99a9275_2    conda-forge
libsolv                   0.7.24               hd84c7bf_1    conda-forge
libsqlite                 3.42.0               h194ca79_0    conda-forge
libssh2                   1.11.0               h492db2e_0    conda-forge
libstdcxx-ng              13.1.0               h452befe_0    conda-forge
libuuid                   2.38.1               hb4cce97_0    conda-forge
libuv                     1.44.2               h31becfc_1    conda-forge
libxcb                    1.15                 h2a766a3_0    conda-forge
libxml2                   2.11.5               h164fba4_0    conda-forge
libzlib                   1.2.13               h31becfc_5    conda-forge
lz4-c                     1.9.4                hd600fc2_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.4.2           py310hcbdc16a_0    conda-forge
ncurses                   6.4                  h2e1726e_0    conda-forge
nodejs                    18.17.1              hcb20a51_0    conda-forge
openssl                   3.1.2                h31becfc_0    conda-forge
openvscode-server         1.80.2               h74955f7_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pcre2                     10.40                he7b27c6_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hb9de7d4_1001    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h761cc84_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.12         hbbe8eec_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h8fc344f_1    conda-forge
reproc                    14.2.4               hb4cce97_0    conda-forge
reproc-cpp                14.2.4               hd600fc2_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               hc770f70_2    conda-forge
ruamel.yaml               0.17.32         py310hb299538_0    conda-forge
ruamel.yaml.clib          0.2.7           py310hb89b984_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               hd8af866_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h3557bc0_1002    conda-forge
xorg-libx11               1.8.6                h055a233_0    conda-forge
xorg-libxau               1.0.11               h31becfc_0    conda-forge
xorg-libxdmcp             1.1.3                h3557bc0_0    conda-forge
xorg-xextproto            7.3.0             h2a766a3_1003    conda-forge
xorg-xproto               7.0.31            h3557bc0_1007    conda-forge
xz                        5.2.6                h9cdd2b7_0    conda-forge
yaml-cpp                  0.7.0                h4de3ea5_2    conda-forge
zlib                      1.2.13               h31becfc_5    conda-forge
zstandard                 0.19.0          py310h468e293_2    conda-forge
zstd                      1.5.2                h4c53e97_7    conda-forge
```

### Environment info

```shell
conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=aarch64
                          __glibc=2.31=0
                          __linux=5.15.49=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-aarch64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/5.15.49-linuxkit ubuntu/20.04.6 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by jtilly** [comment]
I should add that I'm not running into this issue when downloading and running the binary from https://github.com/gitpod-io/openvscode-server/releases/tag/openvscode-server-v1.80.2 directly.

**Comment by xhochy** [comment]
Oh, damn. Didn't see this before merging the new releases. Have you checked whether this happens with all versions or is it limited to the `linux-aarch64` build?

**Comment by xhochy** [comment]
The source of the error is that one builds and runs with two different `nodejs` major versions.

**Comment by xhochy** [comment]
I get the same error with 1.80.2 but it still starts. I guess the more crucial part is

```
[13:11:51] [Error: ENOENT: no such file or directory, scandir '/root/.openvscode-server/data/logs'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/root/.openvscode-server/data/logs'
}
```
